### PR TITLE
Fix #142: Panic when protobuf enum contains comments

### LINKED ISSUE #142: Panic when protobuf enum contains comments
Generating a service from a protobuf service definition which contains an enum defined as follows:
```
...
enum FooBarBaz {
    // This is my comment, this is my note
   FOO = 0;
   BAR = 1;
   BAZ = 2;
}
...
```

Results in a panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xbd94b]

goroutine 1 [running]:
panic(0x2cafc0, 0xc4200140a0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/TuneLab/go-truss/deftree.(*ProtoEnum).GetByName(0xc4203ea050, 0xc42042f1e0, 0x16, 0x4a8da0, 0xc4203ea050)
	<autogenerated>:17 +0x3b
github.com/TuneLab/go-truss/deftree.(*MicroserviceDefinition).SetComment(0xc420397450, 0xc42042ccc0, 0x3, 0x3, 0xc4204315a0, 0x1a)
	/Users/siim/go/src/github.com/TuneLab/go-truss/deftree/deftree.go:149 +0x89
github.com/TuneLab/go-truss/deftree.AssociateComments(0x4a9640, 0xc420397450, 0xc4203eb7c0)
	/Users/siim/go/src/github.com/TuneLab/go-truss/deftree/associate_comments.go:267 +0x93b
github.com/TuneLab/go-truss/deftree.New(0xc4203eb7c0, 0x4a3e20, 0xc4203925d0, 0xc4203925d0, 0x0, 0x0, 0xc4203eb7c0)
	/Users/siim/go/src/github.com/TuneLab/go-truss/deftree/build_deftree.go:84 +0x4cd
main.parseServiceDefinition(0xc420098580, 0x0, 0x3230b9, 0x12, 0x0, 0x0)
	/Users/siim/go/src/github.com/TuneLab/go-truss/cmd/truss/main.go:246 +0x78a
main.main()
	/Users/siim/go/src/github.com/TuneLab/go-truss/cmd/truss/main.go:79 +0xcc
```

### PR DESCRIPTION
**Pull request by hasLeland**
Implements a fix for issue #142 where a placing comments within an Enum in a Protobuf file caused `deftree` to panic.

The bug was that the `ProtoEnum` struct declares itself as implementing the `Describable` interface, but it actually did not; it didn't implement the `GetByName` method, thus the panic when something tried to call that method on that struct causing a nil pointer dereference.

Additionally, this adds a unit test to ensure that comments within enums don't cause panics and that the correct values are parsed.

--------

Also, this sneaks in small changes like spelling fixes in comments, as well as moving the css in generated documentation to the bottom of the document, making generated markdown documentation look better on github.

### CODE REVIEW

File: deftree/associate_comments_test.go [hunk 1]
```diff
@@ -0,0 +1,50 @@
+package deftree
+
+import (
+	_ "fmt"
```
Comment (hasAdamr) [inline deftree/associate_comments_test.go]: Nit: remove

File: deftree/associate_comments_test.go [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+
+	if md == nil {
+		t.Fatalf("The returned Deftree is nil")
+	}
+	got := md.Files[0].Enums[0].Values[0].Description
+	want := "This is my comment, this is my note"
+	if got != want {
+		t.Fatalf("Comment found in Enum is not expected; got = %q, want = %q", got, want)
+	}
+
```
Comment (hasAdamr) [inline deftree/associate_comments_test.go]: Nit: Whitespace.

File: deftree/build_deftree.go [hunk 3]
```diff
@@ -33,18 +33,6 @@ func initGenGo(req *plugin.CodeGeneratorRequest) {
 	gengo.GenerateAllFiles()
 }
 
-func init() {
```
Comment (hasAdamr) [inline deftree/build_deftree.go:36]: Good to remove this :+1:

File: gendoc/generate_markdown.go [hunk 4]
```diff
@@ -74,11 +74,13 @@ func defaultDescribeMarkdown(d deftree.Describable, depth int) string {
 }
 
 func MdMicroserviceDefinition(m *deftree.MicroserviceDefinition, depth int) string {
-	rv := doc_css
+	rv := ""
 	rv += defaultDescribeMarkdown(m, depth)
```
Comment (hasAdamr) [inline gendoc/generate_markdown.go]: How about:
```
rv := defaultDescribeMarkdown(m, depth)
```

Also what does `rv` mean?

File: deftree/deftree.go [hunk 5]
```diff
@@ -369,6 +378,10 @@ func (self *EnumValue) Describe(depth int) string {
 	return rv
 }
 
+func (self *EnumValue) GetByName(s string) Describable {
```
Comment (hasAdamr) [inline deftree/deftree.go]: How about:
```
func (_ *EnumValue) Get...
```

File: deftree/deftree.go [hunk 6]
```diff
@@ -339,6 +339,15 @@ func (self *ProtoEnum) Describe(depth int) string {
 	return rv
 }
 
+func (pe *ProtoEnum) GetByName(name string) Describable {
```
Comment (hasAdamr) [inline deftree/deftree.go:342]: This is not constistant with the reciever name as the methods above it. 

Above they are:

```
func (self *ProtoEnum) ...
```

I like changing it from `self` to `pe` though please update all of them to `pe` if that is the change.

**Review by hasAdamr — COMMENTED** [review]
Nitpicks mostly, looks like the change was pretty straightforward. 

Great job!

File: gendoc/generate_markdown.go (hunk 4 above)
Comment (hasLeland) [reply gendoc/generate_markdown.go]: `rv` is meant to mean "return value".

File: deftree/deftree.go (hunk 6 above)
Comment (hasLeland) [reply deftree/deftree.go:342]: Alright, they've all moved to the better `pe` name.

**Review by hasAdamr — APPROVED** [review]
